### PR TITLE
vendor: switch to the new virtcontainers home

### LINKED ISSUE #1061: Switch to the new virtcontainers home
## Description of problem

Virtcontainers has recently become a Kata Containers component:
https://github.com/kata-containers/runtime/pull/41

## Expected result

The Clear Containers runtime should switch to this new virtcontainers package location.

### PR DESCRIPTION
**Pull request by devimc**
virtcontainers is now part Kata Containers.
This patch is to switch to the new virtcontainers home.
    
shortlog:
ab0724c 1.0.8 release
9bb9779 kata_agent: ipv6: Ignore routes that have ipv6 gateway
f98fa09 hyperstart_agent: ipv6: Ignore routes that have ipv6 gateway
3878df7 oci: apply CPU share constraint

fixes #1061

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks @devimc. Could you add the list of commits as this also updates the version of virtcontainers. I think we have:

    ab0724c 1.0.8 release
    9bb9779 kata_agent: ipv6: Ignore routes that have ipv6 gateway
    f98fa09 hyperstart_agent: ipv6: Ignore routes that have ipv6 gateway
    3878df7 oci: apply CPU share constraint

**Comment by jodh-intel** [comment]
Ah - I suspect you used `sed` to change the source? Can you re-format it with `gofm -w` to make the CI happy? :)

**Comment by sboeuf** [comment]
@devimc looks good, but please add a more verbose commit/PR message.

**Comment by devimc** [comment]
@sboeuf  @jodh-intel  changes applied

**Comment by sboeuf** [comment]
Thanks @devimc 
LGTM

**Pull request merged**
