### PR TITLE
Remove shim

### PR DESCRIPTION
**Pull request by sboeuf**
Based on https://github.com/containers/virtcontainers/pull/201, we can now simplify the code for the runtime and remove all references to shim.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Travis is unhappy with commit c7b4fb7412a7075eab529c6d1fe8ad43e1635852 - did you forget to remove `shim.go` from `.travis.yml`?

**Comment by sboeuf** [comment]
I did forget...

**Comment by sboeuf** [comment]
Better now!

**Comment by jodh-intel** [comment]
lgtm

**Comment by sboeuf** [comment]
@jodh-intel I have added the do-not-merge label in order to wait for https://github.com/containers/virtcontainers/pull/201 to be merged first. Thanks for the review !

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
Let's wait for @dlespiau to review https://github.com/containers/virtcontainers/pull/201 and then we will be able to merge both PRs.

**Comment by dlespiau** [comment]
Probably a good idea to include a new vendoring and make the test pass now that  containers/virtcontainers#201 is merged?

**Comment by sboeuf** [comment]
@dlespiau Tests are passing just fine. The no-go is about the unit test coverage, because it has decreased 2.3%. The reason for this is not because I forgot to add unit tests to some new code, but because I have removed shim code which was pretty well covered. Could you force the merge ? I apparently don't have the right to do that on this repo.

**Comment by dlespiau** [comment]
I don't have the rights either :) @sameo has though.

**Pull request merged**
