### PR TITLE
go 1.9 go vet fixes

### PR DESCRIPTION
**Pull request by mcastelino**
Fix go vet errors detected by go ver 1.9

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by mcastelino** [comment]
@sboeuf @jodh-intel testify fails its own go test which is causing the failure. Our CI runs go test on each of the packages we vendor.

**Comment by mcastelino** [comment]
There seems to be a bug in dep. It somehow excludes two files which are needed for go test to pass.
```
        assertion_format.go
        assertion_format.go.tmpl
```

**Comment by mcastelino** [comment]
@sboeuf @jodh-intel manually adding the dependencies missed out by dep while I try to figure out the bug in dep.

**Comment by sboeuf** [comment]
@mcastelino have you tried latest dep version? Might solve the issue, I don't know...

**Comment by sboeuf** [comment]
Coveralls tag is here: https://coveralls.io/jobs/30125037
Merging the PR

**Pull request merged**
