### PR TITLE
# Release 3.0.15

### PR DESCRIPTION
**Pull request by jcvenegas**
## Changes
Welcome to Clear Container release 3.0.15!
For this release the  virtcontainers package was updated and  now the runtime provides initial support for the Kata Containers [shim](https://github.com/katacontainers/shim), [proxy](https://github.com/katacontainers/proxy)  and [agent](https://github.com/katacontainers/agent) components. With that new code included cc-runtime can be used to create, start, run and list containers with the Kata components.

The documentation was improved by adding information about how to check if your NIC hardware actually supports SR-IOV. Also, the runtime conifguration file describe better the `hypervisor debug option`.

- config: Clean up hypervisor debug comments
- build: Set systemd unit name based on project
- build: Check ".git" is a directory before hook install
- build: Only install git hooks in a git clone
- docs: SR-IOV: Document using lspci to check SR-IOV caps
- installation: RHEL installation script for cc-runtime.
- vendor: Revendor virtcontainers to include Kata Containers support
- build: Add basic architecture framework
- CI: Don't require an issue for release PRs
- scripts: Add missing distros to release script

## Shortlog
512cd59 config: Clean up hypervisor debug comments
9be4882 build: Set systemd unit name based on project
c533374 build: Check ".git" is a directory before hook install
ec227a4 build: Only install git hooks in a git clone
ac6bb96 docs: SR-IOV: Document using lspci to check SR-IOV caps
f775e99 installation: RHEL installation script for cc-runtime.
297cdda vendor: Revendor virtcontainers to include Kata Containers support
9ee2307 build: Add basic architecture framework
794fef7 CI: Don't require an issue for release PRs
93694e6 scripts: Add missing distros to release script

## Compatibility with Docker
Clear Containers 3.0.15 is compatible with Docker v17.12-ce
## OCI Runtime Specification
Clear Containers 3.0.15 support the OCI Runtime Specification [v1.0.0-rc5][ocispec]

## Clear Linux Containers image
Clear Containers 3.0.15 requires at least Clear Linux containers image [19350][clearlinuximage]

## Clear Linux Containers Kernel
Clear Containers 3.0.15 requires at least Clear Linux Containers  kernel [v4.9.60-83.container][kernel]

## Installation

- [BC-Linux][bclinux]
- [Centos][centos]
- [Clear Linux][clearlinux]
- [Fedora][fedora]
- [SLES][sles]
- [Ubuntu][ubuntu]

- [Developers][developers]

### Docker swarm support
See issue [\#771](https://github.com/clearcontainers/runtime/issues/771) for more
#### `docker run --cpus=`
See issue [\#341](https://github.com/clearcontainers/runtime/issues/341) for more information.
#### `docker run --kernel-memory=`
See issue [\#388](https://github.com/clearcontainers/runtime/issues/388) for more information.
#### Capabilities
See issue [\#51](https://github.com/clearcontainers/runtime/issues/51) for more information.
#### `docker stats`
See issue [\#200](https://github.com/clearcontainers/runtime/issues/200) for more information.
#### `ps` command
See issue [\#95](https://github.com/clearcontainers/runtime/issues/95) for more information.
#### `events` command
See issue [\#379](https://github.com/clearcontainers/runtime/issues/379) for more information.
#### `update` command
See issue [\#380](https://github.com/clearcontainers/runtime/issues/380) for more information.
### Host `rdmsr` warnings
More information [Limitations][limitations]

[clearlinuximage]: https://download.clearlinux.org/releases/19350/clear/clear-19350-containers.img.xz
[kernel]: https://github.com/clearcontainers/linux/tree/v4.9.60-83.container
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5
[limitations]: https://github.com/clearcontainers/runtime/blob/de1b8f593fe866ce775d1c6efea682ff7dff7a59/docs/limitations.md
[ubuntu]: https://github.com/clearcontainers/runtime/blob/de1b8f593fe866ce775d1c6efea682ff7dff7a59/docs/ubuntu-installation-guide.md
[fedora]: https://github.com/clearcontainers/runtime/blob/de1b8f593fe866ce775d1c6efea682ff7dff7a59/docs/fedora-installation-guide.md
[centos]: https://github.com/clearcontainers/runtime/blob/de1b8f593fe866ce775d1c6efea682ff7dff7a59/docs/centos-installation-guide.md
[sles]: https://github.com/clearcontainers/runtime/blob/de1b8f593fe866ce775d1c6efea682ff7dff7a59/docs/sles-installation-guide.md
[clearlinux]: https://github.com/clearcontainers/runtime/blob/de1b8f593fe866ce775d1c6efea682ff7dff7a59/docs/clearlinux-installation-guide.md
[bclinux]: https://github.com/clearcontainers/runtime/blob/de1b8f593fe866ce775d1c6efea682ff7dff7a59/docs/bclinux-installation-guide.md
[developers]: https://github.com/clearcontainers/runtime/blob/de1b8f593fe866ce775d1c6efea682ff7dff7a59/docs/developers-clear-containers-install.md

### CODE REVIEW

**Comment by grahamwhaley** [comment]
You might need to massage this bit

 **FIXME - massage this section by hand to produce a summary please** 

in the PR :-)

**Comment by jodh-intel** [comment]
One other thing - the PR shows the shortlog and description, but there is nothing in the commit?

**Comment by jcvenegas** [comment]
@grahamwhaley Yeah after make_ bump.sh do a PR I still need to add the summary manually.

**Comment by jcvenegas** [comment]
@jodh-intel updated, I will add to make_bump.sh to add a shortlog  to the commit message.

**Comment by grahamwhaley** [comment]
heh - np - I wonder if you can get make_bump to do the commit locally and drop you into a `git commit --amend` :-) heh

**Comment by sameo** [comment]
LGTM

**Comment by jcvenegas** [comment]
Failed ubuntu 17.10 , restarting ...
Issue info:
```
00:20:51.728 • Failure [17.455 seconds]
00:20:51.729 docker attach
00:20:51.729 /home/jenkins/jenkins_slave/workspace/clear-containers-runtime-azure-ubuntu-17-10-PR/go/src/github.com/clearcontainers/tests/integration/docker/attach_test.go:25
00:20:51.729   check attach functionality
00:20:51.729   /home/jenkins/jenkins_slave/workspace/clear-containers-runtime-azure-ubuntu-17-10-PR/go/src/github.com/clearcontainers/tests/integration/docker/attach_test.go:45
00:20:51.730     should attach exit code [It]
00:20:51.731     /home/jenkins/jenkins_slave/workspace/clear-containers-runtime-azure-ubuntu-17-10-PR/go/src/github.com/clearcontainers/tests/integration/docker/attach_test.go:46
00:20:51.731 
00:20:51.731     Expected
00:20:51.731         <int>: 1
00:20:51.731     to equal
00:20:51.731         <int>: 13
00:20:51.731 
00:20:51.731     /home/jenkins/jenkins_slave/workspace/clear-containers-runtime-azure-ubuntu-17-10-PR/go/src/github.com/clearcontainers/tests/integration/docker/attach_test.go:48
```
```
00:27:27.686 Summarizing 1 Failure:
00:27:27.686 
00:27:27.686 [Fail] docker attach check attach functionality [It] should attach exit code 
00:27:27.687 /home/jenkins/jenkins_slave/workspace/clear-containers-runtime-azure-ubuntu-17-10-PR/go/src/github.com/clearcontainers/tests/integration/docker/attach_test.go:48
00:27:27.688 
00:27:27.688 Ran 114 of 159 Specs in 436.046 seconds
00:27:27.688 FAIL! -- 113 Passed | 1 Failed | 0 Pending | 45 Skipped --- FAIL: TestIntegration (470.55s)
00:27:27.691 FAIL
```
https://github.com/clearcontainers/tests/blob/master/integration/docker/attach_test.go#L47

**Pull request merged**
