### PR TITLE
ci: minor go-static-checks fixes

### PR DESCRIPTION
**Pull request by grahamwhaley**
Minor fixes to the go-static-checks script

Fixes: #306

Signed-off-by: Graham Whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
lgtm

**Comment by grahamwhaley** [comment]
rebased and pushed to try and clear out Travis problem.

**Comment by devimc** [comment]
@grahamwhaley could try to rebase and push again?

**Comment by grahamwhaley** [comment]
rebased and pushed - let's see if that clears the CI

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
