### PR TITLE
tests: Add unit test for checkConfigParams().

### PR DESCRIPTION
**Pull request by jodh-intel**
Add basic tests for checkConfigParams().

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by devimc** [comment]
lgtm

**Comment by devimc** [comment]
@jodh-intel your branch has conflicts

**Comment by jodh-intel** [comment]
Branch updated.

**Pull request merged**
