### PR TITLE
release: 3.0.5

### PR DESCRIPTION
**Pull request by jcvenegas**
# Release 3.0.5

## Changes
- vendor: Vendor virtcontainers 1.0.4 
- Docs: Update Installation Guide for Ubuntu
- Install doc fixes

## Shortlog
3a894b9 vendor: Pull virtcontainers QMP logger fix
e8f982e create: Fix unit test for new runtime spec
f984bb5 vendor: Vendor virtcontainers 1.0.4 in
5ee5c28 Docs: Update Installation Guide for Ubuntu
a63ce62 docs: Simplify wording in install docs
aeae914 docs: Fix indent in Fedora and Ubuntu install docs
6b24bcf docs: Run all ubuntu install commands non-interactively
6c6df5b docs: Fix syntax error in here document
ee298cc docs: install docs should all specify busybox image

## Compatibility with Docker
Clear Containers 3.0.5 is compatible with Docker v17.09-ce
## OCI Runtime Specification
Clear Containers 3.0.5 support the OCI Runtime Specification [v1.0.0-rc5][ocispec]

## Clear Linux Containers image
Clear Containers 3.0.5 requires at least Clear Linux containers image [18400][clearlinuximage]

## Clear Linux Containers Kernel
Clear Containers 3.0.5 requires at least Clear Linux Containers  kernel [v4.9.54-78.container][kernel]

## Installation
- [Ubuntu][ubuntu]                                         
- [Fedora][fedora]                                         
- [Developers][developers]                                         

#### `docker run --cpus=`
See issue [\#341](https://github.com/clearcontainers/runtime/issues/341) for more information.
#### `docker run --kernel-memory=`
See issue [\#388](https://github.com/clearcontainers/runtime/issues/388) for more information.
#### Capabilities
See issue [\#51](https://github.com/clearcontainers/runtime/issues/51) for more information.
#### `docker stats`
See issue [\#200](https://github.com/clearcontainers/runtime/issues/200) for more information.
#### `ps` command
See issue [\#95](https://github.com/clearcontainers/runtime/issues/95) for more information.
#### `events` command
See issue [\#379](https://github.com/clearcontainers/runtime/issues/379) for more information.
#### `update` command
See issue [\#380](https://github.com/clearcontainers/runtime/issues/380) for more information.
#### `spec` command
More information [Limitations][limitations]

[clearlinuximage]: https://download.clearlinux.org/releases/18400/clear/clear-18400-containers.img.xz
[kernel]: https://github.com/clearcontainers/linux/tree/v4.9.54-78.container
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5
[limitations]: https://github.com/clearcontainers/runtime/blob/39b11f8d84cc7d2139e8a98c19c5a23df2593a28/docs/limitations.md
[ubuntu]: https://github.com/clearcontainers/runtime/blob/39b11f8d84cc7d2139e8a98c19c5a23df2593a28/docs/ubuntu-installation-guide.md
[fedora]: https://github.com/clearcontainers/runtime/blob/39b11f8d84cc7d2139e8a98c19c5a23df2593a28/docs/fedora-installation-guide.md
[developers]: https://github.com/clearcontainers/runtime/blob/39b11f8d84cc7d2139e8a98c19c5a23df2593a28/docs/developers-clear-containers-install.md

### CODE REVIEW

**Comment by chavafg** [comment]
4.0.5?

**Comment by jcvenegas** [comment]
@chavafg thanks for notice the wrong version, now is the correct `3.0.5`.

**Comment by jodh-intel** [comment]
lgtm

**Comment by devimc** [comment]
lgtm

**Pull request merged**
