### PR TITLE
pause: Rewrite pause binary in go.

### LINKED ISSUE #433: Rewrite pause binary in go
Requiring the pause binary be written in C means we need to build it statically. However, this is problematic on RHEL 7, so let's rewrite it in go for now.

See https://github.com/clearcontainers/packaging/issues/38.

### PR DESCRIPTION
**Pull request by jodh-intel**
Requiring a statically-linked C program causes problems on some
platforms (such as RHEL).

Fixes #433.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by jodh-intel** [comment]
Hi @iphutch - please could you review?

**Comment by grahamwhaley** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Comment by gorozco1** [comment]
@jodh-intel in Makefile please remove 

```
override LIBS +=
override CFLAGS += -Os -Wall -Wextra -static
```

**Comment by jodh-intel** [comment]
@gorozco1 - good catch! Done.

**Comment by gorozco1** [comment]
👍  merge, merg, merge!!

**Pull request merged**
