### PR TITLE
# Release 3.0.19

### PR DESCRIPTION
**Pull request by erick0z**
Welcome to Clear Containers 3.0.19 release!

This release includes the Clear Containers support for ARM. Updated the Openshift, Kubernetes and CRI-O versions. A new Makefile target that displays the available arches were introduced. Introduced an architecture framework for ARM.
## Changes

- logger: Fix nanosecond timestamp test
- vendor: Re-vendor virtcontainers to bring ARM support.
- logger: Fix nanosecond timestamps
- build: Add 'show-arches' target
- build: Add architecture framework for ARM
- vendor: Re-vendor virtcontainers to include changes in govmm.
- versions: Update Openshift, Kubernetes and CRI-O

## Shortlog
702ee56 logger: Fix nanosecond timestamp test
e4ec67c vendor: Re-vendor virtcontainers to bring ARM support.
f90b33b logger: Fix nanosecond timestamps
84104b8 build: Add 'show-arches' target
3642602 build: Add variable for arch file suffix
c17c1f0 build: Add missing periods
db882f3 build: Add architecture framework for ARM
db9f440 vendor: Re-vendor virtcontainers to include changes in govmm.
26ce77d versions: Upade openshift, kubernetes, runc and CRI-O

## Compatibility with Docker
Clear Containers 3.0.19 is compatible with Docker v17.12-ce
## OCI Runtime Specification
Clear Containers 3.0.19 support the OCI Runtime Specification [v1.0.0-rc5][ocispec]

## Clear Linux Containers image
Clear Containers 3.0.19 requires at least Clear Linux containers image [20640][clearlinuximage]

## Clear Linux Containers Kernel
Clear Containers 3.0.19 requires at least Clear Linux Containers  kernel [v4.9.60-84.container][kernel]

## Installation

- [BC-Linux][bclinux]
- [Centos][centos]
- [Clear Linux][clearlinux]
- [Fedora][fedora]
- [SLES][sles]
- [Ubuntu][ubuntu]

- [Developers][developers]

### Docker swarm support
See issue [\#771](https://github.com/clearcontainers/runtime/issues/771) for more
#### `docker run --cpus=`
See issue [\#341](https://github.com/clearcontainers/runtime/issues/341) for more information.
#### `docker run --kernel-memory=`
See issue [\#388](https://github.com/clearcontainers/runtime/issues/388) for more information.
#### Capabilities
See issue [\#51](https://github.com/clearcontainers/runtime/issues/51) for more information.
#### `docker stats`
See issue [\#200](https://github.com/clearcontainers/runtime/issues/200) for more information.
#### `ps` command
See issue [\#95](https://github.com/clearcontainers/runtime/issues/95) for more information.
#### `events` command
See issue [\#379](https://github.com/clearcontainers/runtime/issues/379) for more information.
#### `update` command
See issue [\#380](https://github.com/clearcontainers/runtime/issues/380) for more information.
### Host `rdmsr` warnings
More information [Limitations][limitations]

[clearlinuximage]: https://download.clearlinux.org/releases/20640/clear/clear-20640-containers.img.xz
[kernel]: https://github.com/clearcontainers/linux/tree/v4.9.60-84.container
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5
[limitations]: https://github.com/clearcontainers/runtime/blob/10a98930950d600b1a0cfa7da06c2da523a0009b/docs/limitations.md
[ubuntu]: https://github.com/clearcontainers/runtime/blob/10a98930950d600b1a0cfa7da06c2da523a0009b/docs/ubuntu-installation-guide.md
[fedora]: https://github.com/clearcontainers/runtime/blob/10a98930950d600b1a0cfa7da06c2da523a0009b/docs/fedora-installation-guide.md
[centos]: https://github.com/clearcontainers/runtime/blob/10a98930950d600b1a0cfa7da06c2da523a0009b/docs/centos-installation-guide.md
[sles]: https://github.com/clearcontainers/runtime/blob/10a98930950d600b1a0cfa7da06c2da523a0009b/docs/sles-installation-guide.md
[clearlinux]: https://github.com/clearcontainers/runtime/blob/10a98930950d600b1a0cfa7da06c2da523a0009b/docs/clearlinux-installation-guide.md
[bclinux]: https://github.com/clearcontainers/runtime/blob/10a98930950d600b1a0cfa7da06c2da523a0009b/docs/bclinux-installation-guide.md
[developers]: https://github.com/clearcontainers/runtime/blob/10a98930950d600b1a0cfa7da06c2da523a0009b/docs/developers-clear-containers-install.md

### CODE REVIEW

**Comment by devimc** [comment]
one of the highlights in this release is the support for ARM

lgtm

**Comment by erick0z** [comment]
CI failing, possibly due to this issue: https://github.com/clearcontainers/runtime/issues/1017.

**Comment by jodh-intel** [comment]
Confirmed - the bug is due to the fact that we haven't landed #1018 yet.

**Comment by jodh-intel** [comment]
As you haven't tagged the branch, you should be able to rebase this PR to pull in #1018 now its merged.

**Comment by erick0z** [comment]
@jodh-intel Rebased and CI is happy now!

**Comment by jodh-intel** [comment]
Thanks @erick0z!

lgtm

**Pull request merged**
