### PR TITLE
logging: Switch to structured logging

### LINKED ISSUE #633: Implement structured logging
The proxy and agent already use structured logging so switch the runtime to using the same to make the logs more useful (easier to filter and machine-parseable).

### PR DESCRIPTION
**Pull request by jodh-intel**
Use structured or context logging for more useful log messages.

Fixes #633.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
This PR introduces two significant changes:

# Global log format change

Note in particular the change to the time format: timestamp at start of every entry in the old format and `time="..."` field in the new format.

## Old format

```
2017-09-28 09:02:55.900066415 +0100 BST:10236:cc-runtime:info:cc-runtime (version 3.0.0-beta.2, commit f5bc403510ab2a837ba4b2115ea4c94cf51e9dea) called as: [create --bundle /var/run/docker/libcontainerd/5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c --console /dev/pts/1 --pid-file /run/docker/libcontainerd/containerd/5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c/init/pid 5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c]
2017-09-28 09:02:55.905492099 +0100 BST:10236:cc-runtime:info:Using configuration file "/usr/share/defaults/clear-containers/configuration.toml"
2017-09-28 09:02:55.920614681 +0100 BST:10236:cc-runtime:info:No sockets from configuration
2017-09-28 09:02:55.925930084 +0100 BST:10236:cc-runtime:info:Device details for container 5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c: Major:253, Minor:3, MountPoint:/var/lib/docker/devicemapper/mnt/cc25d58b4f85c1a649b76dc802d61b36866c7fd6b47a01884e3b5f5a0260f77f
2017-09-28 09:02:55.931372254 +0100 BST:10236:cc-runtime:info:Block Device path /dev/mapper/docker-253:0-1704608-cc25d58b4f85c1a649b76dc802d61b36866c7fd6b47a01884e3b5f5a0260f77f detected for container with fstype : 5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c
%!(EXTRA string=xfs)
2017-09-28 09:02:56.068927362 +0100 BST:10236:cc-runtime:info:launching qemu with: [-name pod-5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c -uuid 35626466-3038-3162-3731-663931343164 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host,pmu=off -qmp unix:/run/virtcontainers/pods/5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c/monitor.sock,server,nowait -qmp unix:/run/virtcontainers/pods/5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c/ctrl.sock,server,nowait -m 2048M,slots=2,maxmem=3021M -smp 4,cores=4,threads=1,sockets=1 -device virtio-9p-pci,disable-modern=true,fsdev=ctr-9p-0,mount_tag=ctr-rootfs-0 -fsdev local,id=ctr-9p-0,path=/var/lib/docker/devicemapper/mnt/cc25d58b4f85c1a649b76dc802d61b36866c7fd6b47a01884e3b5f5a0260f77f/rootfs,security_model=none -device virtio-serial-pci,disable-modern=true,id=serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/virtcontainers/pods/5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/clear-containers/clear-17270-containers.img,size=235929600 -device virtserialport,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch0,path=/run/virtcontainers/pods/5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c/hyper.sock,server,nowait -device virtserialport,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -chardev socket,id=charch1,path=/run/virtcontainers/pods/5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c/tty.sock,server,nowait -device virtio-9p-pci,disable-modern=true,fsdev=extra-9p-hyperShared,mount_tag=hyperShared -fsdev local,id=extra-9p-hyperShared,path=/tmp/hyper/shared/pods/5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c,security_model=none -device virtio-blk,disable-modern=true,drive=drive-5bdf081b71f9141dbf79e2333,scsi=off,config-wce=off -drive id=drive-5bdf081b71f9141dbf79e2333,file=/dev/mapper/docker-253:0-1704608-cc25d58b4f85c1a649b76dc802d61b36866c7fd6b47a01884e3b5f5a0260f77f,aio=threads,format=raw,if=none -device driver=virtio-net-pci,disable-modern=true,netdev=network-0,mac=02:42:ac:11:00:02 -netdev tap,id=network-0,ifname=tap0,downscript=no,script=no,vhost=on -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/clear-containers/vmlinuz-4.9.47-77.container -append root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k panic=1 console=hvc0 console=hvc1 initcall_debug iommu=off cryptomgr.notests net.ifnames=0 quiet systemd.show_status=false init=/usr/lib/systemd/systemd systemd.unit=clear-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket ip=::::::5bdf081b71f9141dbf79e2333a70de3dc9c9c5fc9fe87e2a062307bdc0d3dd5c::off::]
2017-09-28 09:02:56.133973141 +0100 BST:10236:cc-runtime:info:{"QMP": {"version": {"qemu": {"micro": 1, "minor": 7, "major": 2}, "package": "(2.7.1+git.741f430a96-8.cc)"}, "capabilities": []}}
2017-09-28 09:02:56.144202682 +0100 BST:10236:cc-runtime:info:QMP version 2.7.1
2017-09-28 09:02:56.14964974 +0100 BST:10236:cc-runtime:info:QMP capabilities []
2017-09-28 09:02:56.153911863 +0100 BST:10236:cc-runtime:info:{"execute":"qmp_capabilities"}
2017-09-28 09:02:56.158831351 +0100 BST:10236:cc-runtime:info:{"return": {}}
2017-09-28 09:02:56.163558463 +0100 BST:10236:cc-runtime:info:VM started
2017-09-28 09:02:57.054215334 +0100 BST:10236:cc-runtime:info:Shim(s) started
2017-09-28 09:02:57.067804334 +0100 BST:10236:cc-runtime:info:cgroup path /sys/fs/cgroup/memory mounted
2017-09-28 09:02:57.073371238 +0100 BST:10236:cc-runtime:info:cgroup path /sys/fs/cgroup/cpu mounted
2017-09-28 09:02:57.07796438 +0100 BST:10236:cc-runtime:info:cgroup path /sys/fs/cgroup/pids mounted
2017-09-28 09:02:57.082697586 +0100 BST:10236:cc-runtime:info:cgroup path /sys/fs/cgroup/blkio mounted
```

## New format

```
time="2017-09-28 09:01:00.52291636 +0100 BST" pid=9727 name="cc-runtime" level="info" arguments="create --bundle /var/run/docker/libcontainerd/b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b --console /dev/pts/1 --pid-file /run/docker/libcontainerd/containerd/b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b/init/pid b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b" commit=ad9b7d08675c58cfa2cbbd4cab36332da6f096da name=cc-runtime source=runtime version=3.0.0-beta.2
time="2017-09-28 09:01:00.56735251 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="No sockets from configuration"
time="2017-09-28 09:01:00.575778341 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="Device details for container b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b: Major:253, Minor:3, MountPoint:/var/lib/docker/devicemapper/mnt/335858cfb03ed1f84cd34dc73282e0fe569dfb8b10c5071ae3d0316e4329938c"
time="2017-09-28 09:01:00.582156043 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="Block Device path /dev/mapper/docker-253:0-1704608-335858cfb03ed1f84cd34dc73282e0fe569dfb8b10c5071ae3d0316e4329938c detected for container with fstype : b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b\n%!(EXTRA string=xfs)"
time="2017-09-28 09:01:00.69335586 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="launching qemu with: [-name pod-b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b -uuid 62373133-3334-6539-3534-333339343532 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host,pmu=off -qmp unix:/run/virtcontainers/pods/b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b/monitor.sock,server,nowait -qmp unix:/run/virtcontainers/pods/b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b/ctrl.sock,server,nowait -m 2048M,slots=2,maxmem=3021M -smp 4,cores=4,threads=1,sockets=1 -device virtio-9p-pci,disable-modern=true,fsdev=ctr-9p-0,mount_tag=ctr-rootfs-0 -fsdev local,id=ctr-9p-0,path=/var/lib/docker/devicemapper/mnt/335858cfb03ed1f84cd34dc73282e0fe569dfb8b10c5071ae3d0316e4329938c/rootfs,security_model=none -device virtio-serial-pci,disable-modern=true,id=serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/virtcontainers/pods/b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/clear-containers/clear-17270-containers.img,size=235929600 -device virtserialport,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch0,path=/run/virtcontainers/pods/b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b/hyper.sock,server,nowait -device virtserialport,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -chardev socket,id=charch1,path=/run/virtcontainers/pods/b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b/tty.sock,server,nowait -device virtio-9p-pci,disable-modern=true,fsdev=extra-9p-hyperShared,mount_tag=hyperShared -fsdev local,id=extra-9p-hyperShared,path=/tmp/hyper/shared/pods/b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b,security_model=none -device virtio-blk,disable-modern=true,drive=drive-b71334e9543394521b24ad891,scsi=off,config-wce=off -drive id=drive-b71334e9543394521b24ad891,file=/dev/mapper/docker-253:0-1704608-335858cfb03ed1f84cd34dc73282e0fe569dfb8b10c5071ae3d0316e4329938c,aio=threads,format=raw,if=none -device driver=virtio-net-pci,disable-modern=true,netdev=network-0,mac=02:42:ac:11:00:02 -netdev tap,id=network-0,ifname=tap0,downscript=no,script=no,vhost=on -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/clear-containers/vmlinuz-4.9.47-77.container -append root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k panic=1 console=hvc0 console=hvc1 initcall_debug iommu=off cryptomgr.notests net.ifnames=0 quiet systemd.show_status=false init=/usr/lib/systemd/systemd systemd.unit=clear-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket ip=::::::b71334e9543394521b24ad891efad025c059c63cc75af87b6df5d6e7f37b6f3b::off::]"
time="2017-09-28 09:01:00.861778387 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="{\"QMP\": {\"version\": {\"qemu\": {\"micro\": 1, \"minor\": 7, \"major\": 2}, \"package\": \"(2.7.1+git.741f430a96-8.cc)\"}, \"capabilities\": []}}"
time="2017-09-28 09:01:00.883605382 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="QMP version 2.7.1"
time="2017-09-28 09:01:00.888626244 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="QMP capabilities []"
time="2017-09-28 09:01:00.896116202 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="{\"execute\":\"qmp_capabilities\"}"
time="2017-09-28 09:01:00.903461959 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="{\"return\": {}}"
time="2017-09-28 09:01:00.916731523 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="VM started"
time="2017-09-28 09:01:02.311017261 +0100 BST" pid=9727 name="cc-runtime" level="info" source=virtcontainers msg="Shim(s) started"
time="2017-09-28 09:01:02.32178087 +0100 BST" pid=9727 name="cc-runtime" level="info" path=/sys/fs/cgroup/memory source=runtime type=cgroup msg="path mounted"
time="2017-09-28 09:01:02.326803098 +0100 BST" pid=9727 name="cc-runtime" level="info" path=/sys/fs/cgroup/cpu source=runtime type=cgroup msg="path mounted"
time="2017-09-28 09:01:02.332303881 +0100 BST" pid=9727 name="cc-runtime" level="info" path=/sys/fs/cgroup/pids source=runtime type=cgroup msg="path mounted"
time="2017-09-28 09:01:02.338137467 +0100 BST" pid=9727 name="cc-runtime" level="info" path=/sys/fs/cgroup/blkio source=runtime type=cgroup msg="path mounted"
```

# `cc-check` output change

This change is not essential, but I think it makes sense for *all* logging calls to use structured logging, and `cc-check` generates its output using the logging routines.

## Old format

```
INFO[0000] Found CPU attribute "Intel Architecture CPU" (GenuineIntel)
INFO[0000] Found CPU flag "Virtualization support" (vmx)
INFO[0000] Found CPU flag "64Bit CPU" (lm)
INFO[0000] Found CPU flag "SSE4.1" (sse4_1)
INFO[0000] Found kernel module "Intel KVM" (kvm_intel)
INFO[0000] Kernel module "Intel KVM" parameter "nested" has correct value
INFO[0000] Kernel module "Intel KVM" parameter "unrestricted_guest" has correct value
INFO[0000] Found kernel module "Host kernel accelerator for virtio" (vhost)
INFO[0000] Found kernel module "Host kernel accelerator for virtio network" (vhost_net)
INFO[0000] Found kernel module "Kernel-based Virtual Machine" (kvm)
INFO[0000]
INFO[0000] System is capable of running Intel® Clear Containers
```

## New format

```
INFO[0000] CPU property found                            description="Intel Architecture CPU" name=GenuineIntel source=runtime type=attribute
INFO[0000] CPU property found                            description="Virtualization support" name=vmx source=runtime type=flag
INFO[0000] CPU property found                            description="64Bit CPU" name=lm source=runtime type=flag
INFO[0000] CPU property found                            description=SSE4.1 name="sse4_1" source=runtime type=flag
INFO[0000] kernel property found                         description="Kernel-based Virtual Machine" name=kvm source=runtime type=module
INFO[0000] kernel property found                         description="Intel KVM" name="kvm_intel" source=runtime type=module
INFO[0000] Kernel property value correct                 description="Intel KVM" name="kvm_intel" source=runtime type=module
INFO[0000] Kernel property value correct                 description="Intel KVM" name="kvm_intel" source=runtime type=module
INFO[0000] kernel property found                         description="Host kernel accelerator for virtio" name=vhost source=runtime type=module
INFO[0000] kernel property found                         description="Host kernel accelerator for virtio network" name="vhost_net" source=runtime type=module
INFO[0000] System is capable of running Intel® Clear Containers  source=runtime
```

**Comment by jodh-intel** [comment]
In tandem with https://github.com/containers/virtcontainers/pull/387, this change will make it much easier to work out where log entries originate thanks to the `source=` field:

| "`source=`" value | origin |
|--- | --- |
| `runtime` | `cc-runtime` |
| `proxy` | `cc-proxy` |
| `virtcontainers` | `virtcontainers` |
| `qemu` | `cc-agent` (*) |

(*) - this should probably be changed to `source=vm` or `source=agent`.

**Comment by jodh-intel** [comment]
It's worth pointing out that because `cc-check` already uses the logging routines, if you redirect the output, it will change to structured format currently. But this PR makes the `cc-check` output "more structured":

# Redirected `cc-check` output format

## Old format

```
time="2017-09-28T09:38:56+01:00" level=info msg="Found CPU attribute "Intel Architecture CPU" (GenuineIntel)"
time="2017-09-28T09:38:56+01:00" level=info msg="Found CPU flag "Virtualization support" (vmx)"
time="2017-09-28T09:38:56+01:00" level=info msg="Found CPU flag "64Bit CPU" (lm)"
time="2017-09-28T09:38:56+01:00" level=info msg="Found CPU flag "SSE4.1" (sse4_1)"
time="2017-09-28T09:38:56+01:00" level=info msg="Found kernel module "Kernel-based Virtual Machine" (kvm)"
time="2017-09-28T09:38:56+01:00" level=info msg="Found kernel module "Intel KVM" (kvm_intel)"
time="2017-09-28T09:38:56+01:00" level=info msg="Kernel module "Intel KVM" parameter "nested" has correct value"
time="2017-09-28T09:38:56+01:00" level=info msg="Kernel module "Intel KVM" parameter "unrestricted_guest" has correct value"
time="2017-09-28T09:38:56+01:00" level=info msg="Found kernel module "Host kernel accelerator for virtio" (vhost)"
time="2017-09-28T09:38:56+01:00" level=info msg="Found kernel module "Host kernel accelerator for virtio network" (vhost_net)"
time="2017-09-28T09:38:56+01:00" level=info
time="2017-09-28T09:38:56+01:00" level=info msg="System is capable of running Intel® Clear Containers"
```
## New format

```
time="2017-09-28T09:39:08+01:00" level=info msg="CPU property found" description="Intel Architecture CPU" name=GenuineIntel source=runtime type=attribute
time="2017-09-28T09:39:08+01:00" level=info msg="CPU property found" description="Virtualization support" name=vmx source=runtime type=flag
time="2017-09-28T09:39:08+01:00" level=info msg="CPU property found" description="64Bit CPU" name=lm source=runtime type=flag
time="2017-09-28T09:39:08+01:00" level=info msg="CPU property found" description=SSE4.1 name="sse4_1" source=runtime type=flag
time="2017-09-28T09:39:08+01:00" level=info msg="kernel property found" description="Kernel-based Virtual Machine" name=kvm source=runtime type=module
time="2017-09-28T09:39:08+01:00" level=info msg="kernel property found" description="Intel KVM" name="kvm_intel" source=runtime type=module
time="2017-09-28T09:39:08+01:00" level=info msg="Kernel property value correct" description="Intel KVM" name="kvm_intel" source=runtime type=module
time="2017-09-28T09:39:08+01:00" level=info msg="Kernel property value correct" description="Intel KVM" name="kvm_intel" source=runtime type=module
time="2017-09-28T09:39:08+01:00" level=info msg="kernel property found" description="Host kernel accelerator for virtio" name=vhost source=runtime type=module
time="2017-09-28T09:39:08+01:00" level=info msg="kernel property found" description="Host kernel accelerator for virtio network" name="vhost_net" source=runtime type=module
time="2017-09-28T09:39:08+01:00" level=info msg="System is capable of running Intel® Clear Containers" source=runtime
```

**Comment by jodh-intel** [comment]
Coveralls still stuck - here's the successful report (no change): https://coveralls.io/jobs/29772012

**Comment by grahamwhaley** [comment]
As you've noted, coveralls did pass even if it did not register.
And we know Jenkins 16.04 was in a transition period when this landed, but 17.04 and fedora have passed, so will force merge...

**Comment by jodh-intel** [comment]
@grahamwhaley - ta muchly! ;)

**Pull request merged**
