### PR TITLE
docs: Project now unmaintained

### PR DESCRIPTION
**Pull request by jodh-intel**
Change the `README` to explain Clear Containers is no longer being
maintained and that all users should move to
https://github.com/kata-containers/documentation/tree/master/install.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
@egernst, @grahamwhaley, @sboeuf - I think this is long overdue ;)

As I've got to raise a bunch of these for all the old CC repos, I'm not going to bother creating issues for the `Fixes #XXX` comments and we should just force merge if you agree to this one.

I'll also set all the repos to "archived" as we did for https://github.com/intel/cc-oci-runtime once I've got an ack or two on this PR :)

**Comment by grahamwhaley** [comment]
Oh, I thought we'd done that already! - I am probably mixing it up with the even older `cc-oci-runtime` :-)
LGTM!

**Review by grahamwhaley — APPROVED** [review]
lgtm

**Comment by jodh-intel** [comment]
Re-ping @egernst.

**Comment by egernst** [comment]
to follow up, @jodh-intel is working on process to wind this down.

**Review by egernst — APPROVED** [review]

**Comment by egernst** [comment]
This looks good to me.  It doesn't remove any of the code, etc, but gives an accurate status and recommendation.  Merging.

**Pull request merged**
