### PR TITLE
pullapprove: Require documentation team approval

### PR DESCRIPTION
**Pull request by sameo**
For all documentation files.

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
Looks like the docs team referenced in the config file doesn't exist (yet :)

**Comment by sameo** [comment]
> Looks like the docs team referenced in the config file doesn't exist (yet :)

Fixed now.

**Comment by devimc** [comment]
lgtm

**Comment by rcaballeromx** [comment]
Thanks @sameo

**Comment by sboeuf** [comment]
LGTM

**Pull request merged**
