### PR TITLE
Add standard build targets

### PR DESCRIPTION
**Pull request by jodh-intel**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Replaces #282.

**Comment by dlespiau** [comment]
"standard" is not a great name, system-wide?

**Comment by jodh-intel** [comment]
@dlespiau - yeah, I struggled with the name. `standard-system`?

@sameo, @grahamwhaley - any other thoughts on a meaningful moniker?

**Comment by grahamwhaley** [comment]
In the last patch comment, is there a `not` missing from `This is conventional but does generate
the required configuration for most developers`?

**Comment by grahamwhaley** [comment]
Re: that commit message - it could also do with a mention of what the other prefix is (just `/usr`). If you want me to have a pass at rewriting some of that wording just ping me.
Back to the name..  yeah, lots of imperfect options. To flip @jodh-intel 's around, `system-standard` ? Also, you guys will know better than me, but is this tied to being LSB compliant @jodh-intel @dlespiau - then maybe we can throw that in for a mostly definitive answer.

**Comment by jodh-intel** [comment]
After a ponder, I think `cc-system` is good: it's not overly abstract as the `cc-` prefix denotes Clear Containers of course and that is in-line with our current standard on "non-standard"  options for the runtime itself (commands and flags).

@grahamwhaley - Thanks. I'll fix those typos...

**Comment by jodh-intel** [comment]
Branch updated.

**Comment by devimc** [comment]
lgtm

**Comment by devimc** [comment]
@erick0z @gorozco1  please take a look to this pr

**Comment by jodh-intel** [comment]
@gorozco1, @erick0z - do you guys have any comments on this? The packaging should continue to work, but you might be able to simplify it slightly by making use of these new targets.

**Comment by gorozco1** [comment]
@jodh-intel @devimc yes this PR might change the way the packages are build.. let me make us some tests..

**Comment by erick0z** [comment]
lgtm

**Comment by jodh-intel** [comment]
Hi @gorozco1 - how go the tests?

**Comment by gorozco1** [comment]
@jodh-intel all ok 👍

**Comment by dlespiau** [comment]
Alright no point delaying this more :)

lgtm

**Comment by dlespiau** [comment]
(thanks for testing @gorozco1!)

**Pull request merged**
