### PR TITLE
vendor: Fix runtime by vendoring OCI spec to the proper version

### PR DESCRIPTION
**Pull request by sboeuf**
Runtime was broken by latest vendoring because it removed the OCI runtime specification vendored to the specific version 1.0.0-rc4.

### CODE REVIEW

**Comment by dlespiau** [comment]
+163,599, was that intended?

**Comment by sboeuf** [comment]
result of this command:
```
dep ensure github.com/opencontainers/runtime-spec@a5c4e91dae9533c46a98f122b5085c0b3fe27ee4
```

**Comment by dlespiau** [comment]
Must be something wrong, pruning is missing (that pulls ciao for instance).

**Comment by sboeuf** [comment]
Yeah... I had to vendor to the version and then prune again. Better now

**Comment by dlespiau** [comment]
Thanks!

lgtm

**Pull request merged**
