### PR TITLE
# Release 3.0.17

### PR DESCRIPTION
**Pull request by erick0z**
Welcome to Clear Containers 3.0.17 release!

Thi release the clear containers image was updated to the latest agent version. The agent include changes to  support to online vCPUs and  Linux capabilities. Now it has NoNewPrivileges in the api. Finally, the  agent now is the subreaper of all processes. 

## Changes
- versions: image: Update base os to version 20640
- build: Don't install git hooks when running under a CI

## Shortlog
b0926d4 versions: agent: image: update agent
66f41d6 versions: image: Update base os to version 20640
1c45133 build: Don't install git hooks when running under a CI

## Compatibility with Docker
Clear Containers 3.0.17 is compatible with Docker v17.12-ce
## OCI Runtime Specification
Clear Containers 3.0.17 support the OCI Runtime Specification [v1.0.0-rc5][ocispec]

## Clear Linux Containers image
Clear Containers 3.0.17 requires at least Clear Linux containers image [20640][clearlinuximage]

## Clear Linux Containers Kernel
Clear Containers 3.0.17 requires at least Clear Linux Containers  kernel [v4.9.60-84.container][kernel]

## Installation

- [BC-Linux][bclinux]
- [Centos][centos]
- [Clear Linux][clearlinux]
- [Fedora][fedora]
- [SLES][sles]
- [Ubuntu][ubuntu]

- [Developers][developers]

### Docker swarm support
See issue [\#771](https://github.com/clearcontainers/runtime/issues/771) for more
#### `docker run --cpus=`
See issue [\#341](https://github.com/clearcontainers/runtime/issues/341) for more information.
#### `docker run --kernel-memory=`
See issue [\#388](https://github.com/clearcontainers/runtime/issues/388) for more information.
#### Capabilities
See issue [\#51](https://github.com/clearcontainers/runtime/issues/51) for more information.
#### `docker stats`
See issue [\#200](https://github.com/clearcontainers/runtime/issues/200) for more information.
#### `ps` command
See issue [\#95](https://github.com/clearcontainers/runtime/issues/95) for more information.
#### `events` command
See issue [\#379](https://github.com/clearcontainers/runtime/issues/379) for more information.
#### `update` command
See issue [\#380](https://github.com/clearcontainers/runtime/issues/380) for more information.
### Host `rdmsr` warnings
More information [Limitations][limitations]

[clearlinuximage]: https://download.clearlinux.org/releases/20640/clear/clear-20640-containers.img.xz
[kernel]: https://github.com/clearcontainers/linux/tree/v4.9.60-84.container
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5
[limitations]: https://github.com/clearcontainers/runtime/blob/6ee0c5c8b1b21f4a6227794fc33d0b96ace84547/docs/limitations.md
[ubuntu]: https://github.com/clearcontainers/runtime/blob/6ee0c5c8b1b21f4a6227794fc33d0b96ace84547/docs/ubuntu-installation-guide.md
[fedora]: https://github.com/clearcontainers/runtime/blob/6ee0c5c8b1b21f4a6227794fc33d0b96ace84547/docs/fedora-installation-guide.md
[centos]: https://github.com/clearcontainers/runtime/blob/6ee0c5c8b1b21f4a6227794fc33d0b96ace84547/docs/centos-installation-guide.md
[sles]: https://github.com/clearcontainers/runtime/blob/6ee0c5c8b1b21f4a6227794fc33d0b96ace84547/docs/sles-installation-guide.md
[clearlinux]: https://github.com/clearcontainers/runtime/blob/6ee0c5c8b1b21f4a6227794fc33d0b96ace84547/docs/clearlinux-installation-guide.md
[bclinux]: https://github.com/clearcontainers/runtime/blob/6ee0c5c8b1b21f4a6227794fc33d0b96ace84547/docs/bclinux-installation-guide.md
[developers]: https://github.com/clearcontainers/runtime/blob/6ee0c5c8b1b21f4a6227794fc33d0b96ace84547/docs/developers-clear-containers-install.md

### CODE REVIEW

**Comment by jodh-intel** [comment]
Once the "FIXME" line in the Changes section is removed...

lgtm

**Comment by jcvenegas** [comment]
@grahamwhaley  any idea about the jenkins errror.
```
09:19:21 FATAL: Unable to produce a script file
```

**Comment by jodh-intel** [comment]
@jcvenegas, @grahamwhaley - I think I found out why:

```
java.io.IOException: No space left on device
```

**Comment by grahamwhaley** [comment]
Yep, that would have been my guess. The high level view of the error is that the Jenkins slave service cannot create the script it needs to run.
I'm pretty sure the root cause will be docker eating up disk space with images and items we no longer need (the build servers have sufficient, but limited, storage space). Last time this happened I found and ran a magic 'docker purge old images' type command - I'll go dig that up and put it at the start or end of our Jenkins config command script so we do a 'cleanse cycle' on each build.

**Comment by grahamwhaley** [comment]
OK, it was slightly more complex than that...
We had run out of disk space, but there was more than one reason:
- we had a dangling `fio` test. They create quite a large test file. I suspect this may have been dangling as it was the thing that first hit the out of disk space problem.
  We clean up those test normally here: https://github.com/clearcontainers/tests/blob/master/metrics/storage/fio_job.sh#L233

- we had a bunch of dangling mounts. I suspect those were left over from a recent dangling mount bug we fixed - I've unmounted them.

- we had a bunch of `install-asset.xxxx` files in /tmp. Unclear exactly how they end up there, but @jcvenegas - the trap EXIT code here: https://github.com/clearcontainers/tests/blob/master/.ci/install_asset.sh#L27
looks a little strange to me - we have two 'cleanup' functions and two 'trap EXIT' registrations - feels wrong. Should that be combined into a single catch and cleanup func?

We have diskspace back now, but there is still a bunch in the overlay2 area - I suspect that is linked to our images. The images we have installed all look pretty valid and current, and I'm holding off the `docker system prune` and related calls just yet, as they will I think nuke all our downloaded images that we use for each run, so would only get us a short term fix, and then the next run would download them all again. I will note, adding osbuilder into the mix for image download/create looks like it cost us another ~1Gb image to store ;-)

I'll kick this build again to test it - and we'll have to keep an eye on this. I think we will hit disk issues again, and then we'll have to get smarter again.

**Comment by grahamwhaley** [comment]
The rebuild worked btw.

**Comment by jcvenegas** [comment]
@grahamwhaley I'll send a fix for install_assets.sh

**Pull request merged**
