### PR TITLE
versions: Update agent version

### PR DESCRIPTION
**Pull request by jcvenegas**
Latest agent version fixes issues with exec wrong output.

Fixes: #997

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
cc @sboeuf  @chavafg @erick0z

**Comment by sboeuf** [comment]
LGTM

**Comment by chavafg** [comment]
lgtm

**Comment by jodh-intel** [comment]
@jcvenegas - you win a prize for that PR number! Here ya go...

:balloon: :ice_cream: :cake: :champagne:  :balloon:

lgtm

**Pull request merged**
