### PR TITLE
vendor: Update for virtcontainers, logrus and sys/unix.

### PR DESCRIPTION
**Pull request by jodh-intel**
This change is primarily for [1] to support the introduction of
"runtime list".

--
[1] - https://github.com/containers/virtcontainers/pull/254.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Comment by jodh-intel** [comment]
Hi @sameo - Since the only other reviewer apart from myself is not around for a few days, could you disable the pullapprove hook temporarily to allow this (and then #132) to be merged?

We then need to ensure we have atleast 3 reviewers / project to avoid this scenario :smile:

**Comment by devimc** [comment]
lgtm

**Pull request merged**
