### PR TITLE
vendor: Update vendoring

### LINKED ISSUE #973: vendor: Remove constraints on packages not vendored directly by the runtime
We need to update the way the vendoring is done, by removing unneeded constraints.

### PR DESCRIPTION
**Pull request by sboeuf**
This pull request does 3 things:
- Remove the vendoring constraints from packages not imported directly by the runtime
- Update `Gopkg.toml` for pruning files
- Revendor virtcontainers

Fixes #973 #974 #975

### CODE REVIEW

**Comment by jcvenegas** [comment]
lgtm
Some questions what is the command/way to remove unused dependencies, what is the recommended dep version to use for our projects?

**Comment by sboeuf** [comment]
@jcvenegas as detailed [here](https://github.com/kata-containers/community/blob/master/VENDORING.md#how-to-install-and-update-dep), you should always try to update dep before to use it. It's better to rely on the latest version if possible.

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
Hi @grahamwhaley - could you take a look at the failing metrics ci result please?

**Comment by grahamwhaley** [comment]
Sure. It's a false failure @jodh-intel . A nuttcp UDP bandwidth test scored higher (better) than we expected.
(note - the metrics CI is still somewhat in beta - we are gathering historical data so we can refine its measures of good/bad - thus, it is presently a non-blocking check in github).

**Comment by grahamwhaley** [comment]
and thus, I will merge (the merge button is 'active', just not 'green' because of the (not required) metrics fail. So, this is not a force merge afaict...)

**Comment by jodh-intel** [comment]
Thanks @grahamwhaley. In which case, we can ignore that single issue and merge..

**Pull request merged**
