### PR TITLE
config: Support options for machine types

### LINKED ISSUE #1001: Support options for machine types
# Description of problem

Unable to specify options for machine types in configuration file

# Expected result

Qemu command line should have options for the machine type

```
qemu ... -machine virt,accel=kvm,gic-version=host,usb=off
```

where **gic-version=host,usb=off** are the options

# Actual result

```
qemu ... -machine virt,accel=kvm ....
```

# Solution

add **machine_options** in configuration file

### PR DESCRIPTION
**Pull request by GabyCT**
This will add support for options for machine types.

Fixes #1001

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
I think this is blocked on https://github.com/containers/virtcontainers/issues/624 right?

lgtm

**Comment by grahamwhaley** [comment]
speaking of which - yesterday I think I saw this as `WIP`, but the CIs were still building it - @chavafg @sboeuf - have we set down and implemented the rule as to if `WIP` or `RFC` or `DNM` tell the CIs not to even try - I know I need to put this in place for the metrics CI for instance (that is, set the filters up in the Jenkins plugin).

If you agree we have room to improve, I'll go open an Issue so we can discuss there.

**Comment by jodh-intel** [comment]
Aside: Not that it applies to Clear Containers any more, but I noticed the other day that TravisCI has the ability to skip builds with a magic commit message tag:

- https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by grahamwhaley** [comment]
Yep. Jenkins github plugins can filter on patterns - iirc both on subject line patterns and labels - need to check the details though.

**Comment by devimc** [comment]
depends-on https://github.com/containers/virtcontainers/pull/614

**Comment by GabyCT** [comment]
Closing this PR as we do not want the user to have control on the machine options

**Pull request closed without merging**
