### PR TITLE
3.0.0-alpha.3 release

### PR DESCRIPTION
**Pull request by dlespiau**
Renamed --all to --cc-all
Added proxy and shim versions to cc-env
Improved test coverage

Shortlog:

c47a61f list: Rename option "--all" to "--cc-all".
818f4e5 docs: No need to install the virtcontainers pause package
2b7a161 docs: update developers-clear-containers-install.md
fe0f373 config: Remove unused variable
28d75ae config: Give TOML table type variables better names.
40af051 cc-env: Add in proxy and shim version details.
14e481f utils: Add a runCommand() helper function.
b3d30cd tests: Move testFileMode to main_test.go
799394c tests: Make testDirMode const.
f7759ac general: Rename cli commands.
433259f tests: Add a unit test version.go
5169afd create: Add Clear Containers specific kernel parameters
0435ecf vendor: Update virtcontainers vendoring
5bea53c build: Add containers/virtcontainers pause binary
18e9f4b tests: Increase unit test coverage for cc-check.go
5d0be97 cc-check: Add const for success message.
b10985f tests: Remove comment.
5f0248b cc-env: Increase test coverage for cc-env.go
fe099f6 cc-env: Simplify showSettings().
50e9681 cc-env: Remove redundant checks.
b7195d7 utils: Add comments and remove erroneous whitespace.

Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
lgtm

**Comment by grahamwhaley** [comment]
grrr, looks like you hit this 'travis bad commit' problem. A re-push has been seen to fix this.
This has been cropping up across repos all week - if it continues next week then I think we are going to have to track it down and fix or report to Travis.

**Comment by dlespiau** [comment]
This PR has now a Fixes tag, but checkcommits says it hasn't...

**Comment by jodh-intel** [comment]
Hi @dlespiau - the problem is your clever "Fixes #XXX" line as `checkcommits` needs to match `Fixes #\d+` - it can't cope with URLs (but feel free to riaise a PR to add that feature ;)

**Comment by dlespiau** [comment]
oh, well. Having the URL there is quite nice to just click on it from `git log`, most definitely something we want! :)

**Comment by grahamwhaley** [comment]
I didn't see the 'magic URL', so wen't to check what the github rules are - it does say here https://help.github.com/articles/closing-issues-via-commit-messages/#closing-an-issue-in-a-different-repository that you can use (semi?) URLs to reference other repos. I was just wondering if a full http://.... URL would be picked up by github for an auto close (if that is the type of url we had).

**Pull request merged**
