### PR TITLE
Allow exec command to specify a different console

### PR DESCRIPTION
**Pull request by sboeuf**
Instead of using the console related to the container, a new process run on an existing container can have its own console.

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by sboeuf** [comment]
@dlespiau sorry I should have mentioned to wait for virtcontainers patches to be merged first... In case of vendoring, please check that we actually have merged this into virtcontainers master, before to merge in the runtime.

**Comment by dlespiau** [comment]
or mark the PR as do-not-merge :)

**Comment by sboeuf** [comment]
Yeah I know I forgot to do that, shame on me!

**Pull request merged**
