### PR TITLE
docs: Mention "make help" in developer doc.

### PR DESCRIPTION
**Pull request by jodh-intel**
Add a note explaining that "make help" can be used to obtain further
information on the build system.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
lgtm

**Comment by jodh-intel** [comment]
Hi @iphutch - could you review please?

**Comment by sboeuf** [comment]
lgtm

**Comment by devimc** [comment]
lgtm

**Pull request merged**
