### PR TITLE
vendor: Update vendoring to master branches

### PR DESCRIPTION
**Pull request by sboeuf**
This patch performs three steps:
- Remove the old dep vendoring (obsolete)
- Fix the build relying on upstream packages
- Enables the new dep vendoring relying on master branches

### CODE REVIEW

**Comment by sboeuf** [comment]
Fixes #215

**Comment by sboeuf** [comment]
Don't merge until we get https://github.com/containers/virtcontainers/pull/292 merged. It has to be slightly modified to rely on virtcontainers master branch and not only the specific sha1 corresponding to the commit.

**Comment by jodh-intel** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Pull request merged**
