### PR TITLE
Remove global log

### LINKED ISSUE #788: Drop the global logger and switch to syslog/journald
The runtime has a [global logfile](https://github.com/clearcontainers/runtime#global-logfile). This concept was added in the early days of Clear Containers as it was useful to have a persistent log of all container activity. This was particularly important for containers that fail since, under Docker, if a container fails to be created, Docker will delete all trace of the container which made debugging tricky ;)

At the time of its introduction, the system had fewer components, but now we have the shim and the proxy (and the agent indirectly) logging to syslog/journald, it makes sense to be consistent and log everything to the same place.

By dropping the global logfile feature and making the runtime use syslog/journald instead, we get all the obvious benefits of using the system log facility (like making life easier for admins, remote logging, etc).

@sameo, @grahamwhaley, @sboeuf, @mcastelino - what's your vote?

### PR DESCRIPTION
**Pull request by jodh-intel**
logger: Switch to system log
    
    Remove the global logfile feature and use the system log
    (syslog/journald) instead. This is for consistency with the other
    components, allowing for easier overall analysis.
    
    Fixes #788.
    
    Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by jodh-intel** [comment]
Hi @chavafg - can you see why this is failing under 16.04?

**Comment by chavafg** [comment]
hi @jodh-intel , I just see this error:
```
Error parsing coverage: open profile.cov: no such file or directory
Build step 'Execute shell' marked build as failure
```
is that coveralls?

**Comment by sboeuf** [comment]
Error parsing coverage: open profile.cov: no such file or directory

@jodh-intel @chavafg yes apparently the coveralls coverage file `profile.cov` has not been generated...

**Comment by jodh-intel** [comment]
/me puts a coin in the slot and pulls the rebuild handle...

**Comment by jodh-intel** [comment]
nice: :slot_machine:

**Comment by jodh-intel** [comment]
how long before we can actually communicate fully in emoji I wonder.

**Comment by jodh-intel** [comment]
Hi @iphutch - please can you review?

**Comment by jodh-intel** [comment]
@devimc, @grahamwhaley - could you take a look please?

**Comment by jodh-intel** [comment]
Coveralls job: https://coveralls.io/jobs/30979808.

Merging...

**Pull request merged**
