### PR TITLE
doc: limitations: fix typo (repeated word)

### LINKED ISSUE #915: There's a typo in limitations.md
Two with repeated:

> The --net=host option can still be used with runc containers and inter-mixed **with with** running cc-runtime containers, thus still enabling use of --net=host when necessary.

### PR DESCRIPTION
**Pull request by warmchang**
doc: limitations: fix typo (repeated word)

Fixes #915 .

Signed-off-by: William Zhang <warmchang@outlook.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@warmchang Thanks! for the fix - this PR is going to fail the CI as the commit does not follow the layout as specified at: https://github.com/clearcontainers/runtime/blob/master/CONTRIBUTING.md#patch-format

We'll let that run and fail. Given the nature of the patch though, we might just force the PR though - what do you think @jodh-intel ?

Oh, I've just noticed/realised you do not have a 'signed-off-by' in your commit either - that one we are going to need I'm afraid, to keep clean the contribution trail. Can you sign your commit off for us please?, and whilst you are there - if you fancy making an Issue and adding a Fixes line and fixing the subject line to have the correct `doc: limitations: fix typo` style as well?

thanks!

**Comment by grahamwhaley** [comment]
(and looks like we crossed messages - thanks for the signed off by ;-) )

**Comment by warmchang** [comment]
Finally, GitHub web site can be accessed normally.

@grahamwhaley sorry I didn't notice the contribution rule and thank you for reminding me! 

I submit an issue, committed with 'signed-off-by' and modified the PR info according to the process.
Please recheck it. ;-)

**Comment by jcvenegas** [comment]
lgtm

**Comment by jcvenegas** [comment]
@klynnrif  could you review this PR?

**Comment by jcvenegas** [comment]
@grahamwhaley @jodh-intel @devimc  can you give it a lgtm here ?

**Comment by jcvenegas** [comment]
and merge it :)

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
Thanks @warmchang ! Merging...

**Pull request merged**
