### PR TITLE
vendor: Update virtcontainers vendoring

### LINKED ISSUE #806: Update virtcontainers vendoring
A new vendoring update is needed in order to get the qemu 2.9 working.

### PR DESCRIPTION
**Pull request by sboeuf**
vendor: Update virtcontainers vendoring
    
    The most important part is that we are revendoring here to include
    patches related to coldplug/hotplug of devices. This way, the qemu
    2.9 can properly work with it.
    
    7e80438 container: fix device mapper hot plug in qemu 2.9
    121a37c filesystem: Fix fetchFile behaviour for devicesFileType
    07593f0 block: Skip cold-plugging block devices.
    4132cd6 api: Simplify drive hotplugging
    74be935 network: Add interface type to our network info
    5718a68 network: Cleanup and optimizations
    a7935fd storage: Simplify fetches from storage
    d8055a6 network: cni: Fix lack of support for SRIOV
    06c73de network: Move fully to netlink structures
    af12f75 network: Replace CNI Result structure with a larger one
    35aafe8 vendor: Update CNI related repositories
    
    Fixes #806

### CODE REVIEW

**Comment by devimc** [comment]
lgtm

**Comment by sboeuf** [comment]
@devimc please merge this when the CI will be okay !

**Comment by sameo** [comment]
LGTM

**Comment by devimc** [comment]
@sboeuf sure

**Comment by jodh-intel** [comment]
lgtm.

Random comment: if you indent the list of commits, github will render that block in a fixed font which looks purtier! ;)

**Pull request merged**
