### PR TITLE
versions: Update agent version to pull in SCSI support

### LINKED ISSUE #1026: Update agent version to pull in support for SCSI

### PR DESCRIPTION
**Pull request by amshinde**
This version of agent has support for SCSI.

Fixes #1026

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by sboeuf** [comment]
@devimc @jodh-intel @grahamwhaley PTAL

**Comment by jodh-intel** [comment]
lgtm

**Comment by amshinde** [comment]
@sboeuf Can you merge this one ? Looks like the metric CI has been added recently and been failing for other PRs as well?

**Pull request merged**
