### PR TITLE
Docs: Update installation guide for Ubuntu

### LINKED ISSUE #732: Update Ubuntu install guide for 16.10 and 17.04 (and 17.10 tomorrow!)
The [Ubuntu install guide](/clearcontainers/runtime/blob/master/docs/ubuntu-installation-guide.md) needs to be tested on Ubuntu 16.10, 17.04 and (as of 19 October) 17.10), and the text updated to state it supports these releases.

(For 17.10 we'll need @gorozco1's help to update OBS).

Related #731.

### PR DESCRIPTION
**Pull request by GabyCT**
This installation guide is for ubuntu 16.10 and 17.04.

Fixes #732

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm.

@iphutch - could you take a look please?

**Comment by gorozco1** [comment]
17.10 is out today and we have packages released for that distro as well.

**Comment by jodh-intel** [comment]
Thanks @gorozco1! I think to support 17.10, we just need to wait for docker to catch up (as much better to use proper distro packages for docker than their "static" builds):

- https://download.docker.com/linux/ubuntu/dists/

**Comment by jodh-intel** [comment]
Hi @GabyCT - can you rebase this PR to resolve the conflict? We can then merge this.

**Pull request closed without merging**
