### PR TITLE
Release 3.0.6

### PR DESCRIPTION
**Pull request by jcvenegas**
- Version bump
- Update Clear Containers image to latest version.

# Release 3.0.6

## Changes
**FIXME - massage this section by hand to produce a summary please (WIP)** 
- docs: Install doc fixes
- Vendoring: Switch to fixed revision vendoring
- Networking: Revendor netlink and virtcontainers to support macvtap
- Improve docker failure message harder
- docs: Document how and when we update the assets
- Improve test info msgs
- pause: Remove everything related to pause binary
- docs: Add Kubernetes section to the architecture document
- Unit test coverage fixes
- versions: Update assets versions

## Shortlog
871f4c7 docs: Install doc fixes
774878a Vendoring: Switch to fixed revision vendoring
1d95e00 Networking: Revendor netlink and virtcontainers to support macvtap
12e966e tests: Show error output if docker not contactable
e2c9ea4 utils: Don't error immediately if runCommandFull() fails
bedb77b docs: Document how and when we update the assets
3e2a6e8 tests: Display error if docker not running
ba52c19 tests: Show uid+gid when running unit tests
a94e58b tests: Add error message before failing in setup
e2ab836 pause: Remove everything related to pause binary
f9d2d07 vendor: Update virtcontainers vendoring
86e938c docs: Add Kubernetes section to the architecture document
a476708 tests: Increase unit test coverage
5ecfa3b cc-check: Remove unnecessary error return
2ec4974 config: Don't check for hypervisor config files twice
e11b202 utils: Format writeFile()
178a9ed versions: Update assets versions

## Compatibility with Docker
Clear Containers 3.0.6 is compatible with Docker v17.09-ce
## OCI Runtime Specification
Clear Containers 3.0.6 support the OCI Runtime Specification [v1.0.0-rc5][ocispec]

## Clear Linux Containers image
Clear Containers 3.0.6 requires at least Clear Linux containers image [18770][clearlinuximage]

## Clear Linux Containers Kernel
Clear Containers 3.0.6 requires at least Clear Linux Containers  kernel [v4.9.58-79.container][kernel]

## Installation
- [Ubuntu][ubuntu]
- [Fedora][fedora]
- [Developers][developers]

#### `docker run --cpus=`
See issue [\#341](https://github.com/clearcontainers/runtime/issues/341) for more information.
#### `docker run --kernel-memory=`
See issue [\#388](https://github.com/clearcontainers/runtime/issues/388) for more information.
#### Capabilities
See issue [\#51](https://github.com/clearcontainers/runtime/issues/51) for more information.
#### `docker stats`
See issue [\#200](https://github.com/clearcontainers/runtime/issues/200) for more information.
#### `ps` command
See issue [\#95](https://github.com/clearcontainers/runtime/issues/95) for more information.
#### `events` command
See issue [\#379](https://github.com/clearcontainers/runtime/issues/379) for more information.
#### `update` command
See issue [\#380](https://github.com/clearcontainers/runtime/issues/380) for more information.
#### `spec` command
More information [Limitations][limitations]

[clearlinuximage]: https://download.clearlinux.org/releases/18770/clear/clear-18770-containers.img.xz
[kernel]: https://github.com/clearcontainers/linux/tree/v4.9.58-79.container
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5
[limitations]: https://github.com/clearcontainers/runtime/blob/ea5b9bba0809ce51ff69865456a048bc33bbc618/docs/limitations.md
[ubuntu]: https://github.com/clearcontainers/runtime/blob/ea5b9bba0809ce51ff69865456a048bc33bbc618/docs/ubuntu-installation-guide.md
[fedora]: https://github.com/clearcontainers/runtime/blob/ea5b9bba0809ce51ff69865456a048bc33bbc618/docs/fedora-installation-guide.md
[developers]: https://github.com/clearcontainers/runtime/blob/ea5b9bba0809ce51ff69865456a048bc33bbc618/docs/developers-clear-containers-install.md

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by devimc** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Comment by grahamwhaley** [comment]
heh - you still have this in the txt, which makes me think you didn't....
```
FIXME - massage this section by hand to produce a summary please (WIP)
```

**Comment by gorozco1** [comment]
@jcvenegas  @sboeuf  Is there any important changes to get into a rootfs image?

ie: a merge was done in the agent just an hour ago

https://github.com/clearcontainers/agent/pull/145

**Comment by jcvenegas** [comment]
@sboeuf  there are some fixes, but the image will not be ready for this release. Will need to wait for the next release for that.

**Comment by sboeuf** [comment]
@jcvenegas fair enough, but let's make sure we get agent fixes next week ;)

**Pull request merged**
