### PR TITLE
refactor: simplify code to return the fastpath first

### PR DESCRIPTION
**Pull request by allencloud**
Hi, my friends, 

Today I spend some time in learning this project clearcontainers/runtime, and will try to use this in the own company's virtualization environment. 

What is amazing project this is! I found that you guys organized and maintained the project so well.

I would be excited if I could be involved in this project. While when I am learning the project, I found that maybe there is some place where we could improve a bit.

What I did:
1. simplify some codes;
2. use `return fast` to eliminate some `else` block, since I think this will make codes ident less to be more readable.

fixes https://github.com/clearcontainers/runtime/issues/623

Although these are all tiny changes, feel free to tell me if I could make more improvement.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @allencloud - thanks very much for your interest and for raising this!

Our CI uses a tool called [checkcommits](https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits) to ensure all PRs take a consistent approach. To make that tool happy, there are a few quick things to do to your commit:

- Change the first line in your commit to have a "subsystem string" (basically it needs to be in the format "something: blah blah blah"). For this PR, you could change it to something like:
  ```
  refactor: simplify code to return the fastpath first
  ```
- Create an issue for the change and then add a `Fixes #XXX` comment at the end of your commit.
  (see https://github.com/clearcontainers/runtime/blob/master/CONTRIBUTING.md#closing-issues).

- Add a brief description to the body of the commit.

It should then look something like this:

```
refactor: simplify code to return the fastpath first

A line or two explaining what you did. blah blah
blah.

Fixes #XXX.

Signed-off-by: Allen Sun <shlallen1990@gmail.com>
```

Thanks again.

**Comment by sameo** [comment]
Once `checkcommit` passes:

LGTM

**Comment by sboeuf** [comment]
@allencloud This looks good, thanks for the PR. Please follow @jodh-intel instructions to update your commit message, otherwise our CI won't be successful and we won't be able to merge your PR.
LGTM

**Comment by allencloud** [comment]
Thanks a lot for all of your advice and feedbacks. @jodh-intel @sameo @sboeuf 
I have updated the commit message as the instructions. PTAL. Thanks a lot.

**Comment by jodh-intel** [comment]
lgtm. Just waiting for coveralls now...

**Comment by sboeuf** [comment]
I have re-triggered the build of 16.04, this should re-generate the coverage.

**Comment by jodh-intel** [comment]
@sboeuf - something is still wrong but I don't know what. Jenkins finished successfully and has logged the coveralls job for this PR, which looks good (no coveralls change): https://coveralls.io/jobs/29666488.

**Comment by jodh-intel** [comment]
Again, coveralls is "stuck": it ran and was successful:

- https://coveralls.io/jobs/29666488

Merging.

Thanks again @allencloud !

**Pull request merged**
