### PR TITLE
centos: Update CentOS documentation

### PR DESCRIPTION
**Pull request by erick0z**
SLES documentation was created based on the CentOS document. Some
updates were made to add more clarity to the installation steps. This
commit adds the updates back to the CentOS guide.

Fixes: #864

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
Hi @klynnrif - could you review please?

**Comment by jodh-intel** [comment]
Hi @klynnrif - please could you review?

**Comment by klynnrif** [comment]
@jodh-intel This lgtm 👍 If I need to take additional action on this let me know. Thanks!

**Comment by jodh-intel** [comment]
Hi @klynnrif - thanks, but please can you add the "lgtm" comment at the start of a line to trigger the approval (this is documented here, but admittedly it doesn't exactly stand out https://github.com/clearcontainers/runtime/blob/master/CONTRIBUTING.md#reviews :-)

**Comment by klynnrif** [comment]
@jodh-intel ...someday I'll have it down :) Thanks!

**Comment by jodh-intel** [comment]
pullapprove seems to be "stuck" as it's ignoring the doc team approval. As we're all happy with this, merging...

**Pull request merged**
