### PR TITLE
build: Add architecture framework for ARM

### LINKED ISSUE #1008: failed to build cc-runtime on ARM
# Description of problem

failed to build cc-runtime on ARM

# Expected result

cc-runtime binary

# Actual result

Makefile:35: arch/arm64-options.mk: No such file or directory
make: *** No rule to make target 'arch/arm64-options.mk'.  Stop.

---
configuration file should have `qemu-system-aarch64` as qemu command and `kvm` as machine accelerator

### PR DESCRIPTION
**Pull request by GabyCT**
This will add the support for ARM architecture.

Fixes #1008

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
This is affected by https://github.com/clearcontainers/tests/pull/915

**Comment by devimc** [comment]
lgtm

**Comment by jodh-intel** [comment]
lgtm.

(Obviously, we'll need https://github.com/containers/virtcontainers/pull/614 for full ARM64 support).

**Comment by jodh-intel** [comment]
Coveralls: https://coveralls.io/jobs/33813014.

**Pull request merged**
