### PR TITLE
proxy: Use one proxy instance per VM

### LINKED ISSUE #795: Use one proxy per VM
Modify runtime to launch one proxy per VM. This will improve our HA story since there will no longer be a single point of failure on the system (the system-level instance of `cc-proxy`).

# Plan (ordered steps)

- [x] Update the proxy to allow 1 proxy / pod, alongside the system-level systemd `cc-proxy` service (https://github.com/clearcontainers/proxy/pull/167).
  At this point:
  - multiple instances of `cc-proxy` will be *able* to co-exist with the system-level `cc-proxy` systemd service.
- [x] Update virtcontainers to spawn 1 proxy / pod (https://github.com/containers/virtcontainers/pull/483).
- [x] Re-vendor the virtcontainers changes into the runtime (#835).
  At this point:
  - the system-level `cc-proxy` systemd instance won't be being used (although it can continue to run without interfering with the pod-specific `cc-proxy` instances).
  - we will lose the KSM feature of `cc-proxy` because since all the proxy requests will be handled by the pod-specific `cc-proxy` instances and since we don't want multiple proxies fighting over KSM kernel settings, the KSM code will never be run.
- [ ] Create a daemon to replace the KSM functionality in `cc-proxy` (https://github.com/clearcontainers/proxy/issues/168).
- [ ] Remove the following features from the proxy:
  - KSM.
  - socket activation.
  - handling code for >1 pods.
- [ ] Update packaging for the proxy to do the following:
  ```
   $ sudo systemctl stop cc-proxy.socket
   $ sudo systemctl stop cc-proxy.service
   $ sudo rm /lib/systemd/system/cc-proxy.socket
   $ sudo rm /lib/systemd/system/cc-proxy.service
   $ sudo systemctl daemon-reload
  ```
- [ ] Release updated packages for proxy, runtime and the new KSM daemon.
  At this point, there will no longer be a system-level `cc-proxy` instance.

### PR DESCRIPTION
**Pull request by jodh-intel**
Re-vendor virtcontainers and update the runtime to move to using one
proxy instance for each VM (pod). Also incorporates requires runtime
changes to take account of virtcontainers API changes.

virtcontainers changes since last re-vendor:

    01b012b vendor: Move the ciao vendoring to ciao-project
    148b06a proxy: Launch one proxy instance per pod
    619300a proxy: Use CC3 proxy path
    d8f2a22 shim: Only show shim-count if there are any
    c993e45 shim: Quote urls in error

Fixes #795.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Here is the "proper" PR that replaces #833. This will unbreak the virtcontainers tests (which pull in the runtime code), *but* this PR is going to fail at the CI stage until we get a new `clear-containers-image` package on the CI systems that includes https://github.com/clearcontainers/agent/pull/160.

@erick0z, @gorozco1 - we might need to create a new `clear-containers-image` package early including the latest agent code.

/cc @sboeuf, @chavafg, @sameo.

Adding dnm tag to flag that this will break the CI tests currently.

**Comment by chavafg** [comment]
Took a look at the logs and see these failures from unit tests:

```
16:40:22 INFO: Running 'go test' as current user on packages '.' with flags '-v -race -timeout 10s'
16:40:28 # github.com/clearcontainers/runtime
16:40:28 ./cc-env_test.go:137: unknown field 'URL' in struct literal of type ProxyInfo
16:40:28 ./cc-env_test.go:746: unknown field 'URL' in struct literal of type ProxyInfo
16:40:28 ./config_test.go:143: unknown field 'URL' in struct literal of type virtcontainers.CCProxyConfig
16:40:28 ./config_test.go:510: unknown field 'URL' in struct literal of type virtcontainers.CCProxyConfig
16:40:28 ./config_test.go:789: p.url undefined (type proxy has no field or method url)
16:40:28 ./config_test.go:789: undefined: defaultProxyURL
16:40:28 ./config_test.go:792: p.URL undefined (type proxy has no field or method URL)
16:40:28 ./config_test.go:793: p.url undefined (type proxy has no field or method url)
16:40:28 FAIL	github.com/clearcontainers/runtime [build failed]
16:40:28 make: *** [Makefile:307: check-go-test] Error 2
16:40:28 Build step 'Execute shell' marked build as failure
```

**Comment by jodh-intel** [comment]
Ouch - fixing...

**Comment by jodh-intel** [comment]
Branch updated.

**Comment by gorozco1** [comment]
cc @jcvenegas

**Comment by jcvenegas** [comment]
@jodh-intel  the image with last agent changes is out, can review https://github.com/clearcontainers/tests/pull/761

**Comment by jodh-intel** [comment]
Hi @jcvenegas - thanks - I've re-pushed to trigger a re-test.

However, I was actually expecting the tests to fail before the agent was updated on https://github.com/clearcontainers/tests/pull/761, so I _don't_ think this should be part of todays release - we need to understand the results before it's merged.

**Comment by jodh-intel** [comment]
I've re-tested this branch with 3.0.9 and it's all working fine.

Also confirmed that this PR fails when testing with image version `19030`, but passes with `19070` and `19350` (which contain the required agent changes).

**Comment by jodh-intel** [comment]
@grahamwhaley, @sameo - could you review so we can unbreak the virtcontainers builds?

**Comment by sameo** [comment]
LGTM

**Pull request merged**
