### PR TITLE
Release: 3.0.0-beta.1

### PR DESCRIPTION
**Pull request by jcvenegas**
# Release 3.0.0-beta.1

#### Switch to the new agent
Clear Containers VM now uses a new VM-agent. The VM-agent allows to spawn processes on behalf of
pod/container(s) running inside the virtual machine. The runtime now uses  [Clear Containers Agent](https://github.com/clearcontainers/agent) by default.The `Clear Containers Agent`  relies heavily on libcontainer used by runc (standard to run containers on bare metal).

#### QEMU machine type change
 Switched from pc-lite to pc machine type.  In the long term we are looking to move to an upstream-QEMU supplied machine type which includes some of the optimizations that were made for Clear Containers. In the short term we have encountered issues around functional support of PCI hotplug and vhost-user support in pc-lite, so made the decision to move to pc while we await a fully supported upstream option.  As a result of this change, the runtime is now booting using a compressed kernel (vmlinuz).
### docs: 
Document limitations.
### config: 
support kernel parameters
### build: 
configuration file depends on build variables

## Shortlog
687b420 runtime: Switch to the new agent
8a38fa7 qemu: Move from pc-lite to pc machine type
56e96d3 docs: Document limitations.
528772f config: support kernel parameters
2c456d7 build: configuration file depends on build variables

## Compatibility with Docker
Clear Containers 3.0.0-beta.1 is compatible with Docker v17.06-ce
## OCI Runtime Specification
Clear Containers 3.0.0-beta.1 support the OCI Runtime Specification [1.0.0-rc5][ocispec]

## Clear Linux Containers image
Clear Containers 3.0.0-beta.1 requires at least Clear Linux containers image [16910][clearlinuximage]

## Clear Linux Containers Kernel
Clear Containers 3.0.0-beta.1 requires at least Clear Linux Containers  kernel [cc-linux-4.9.35][kernel]

## Installation
- [Ubuntu][ubuntu]                                         
- [Fedora][fedora]                                         
- [Developers][developers]                                         

## Issues & limitations
[Limitations][limitations]

[clearlinuximage]: https://download.clearlinux.org/releases/16910/clear/clear-16910-containers.img.xz
[kernel]: https://github.com/clearcontainers/linux/tree/cc-linux-4.9.35
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5
[limitations]: https://github.com/clearcontainers/runtime/blob/14d8084822980341ee9cc656eb4b42d7991a0fb6/docs/limitations.md
[ubuntu]: https://github.com/clearcontainers/runtime/blob/14d8084822980341ee9cc656eb4b42d7991a0fb6/docs/ubuntu-installation-guide.md
[fedora]: https://github.com/clearcontainers/runtime/blob/14d8084822980341ee9cc656eb4b42d7991a0fb6/docs/fedora-installation-guide.md
[developers]: https://github.com/clearcontainers/runtime/blob/14d8084822980341ee9cc656eb4b42d7991a0fb6/docs/developers-clear-containers-install.md

### CODE REVIEW

**Comment by egernst** [comment]
should we add blurb here about the major changes?  ie: agent + move to PC machine type?

**Comment by amshinde** [comment]
ping @devimc

**Comment by mcastelino** [comment]
LGTM

**Comment by grahamwhaley** [comment]
The link to the OCI runtime is malformed - missing `v`. Should be:
https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5

**Comment by devimc** [comment]
lgtm

**Comment by devimc** [comment]
@grahamwhaley link fixed

**Pull request merged**
