### PR TITLE
# Release 3.0.16

### PR DESCRIPTION
**Pull request by jcvenegas**
Welcome to Clear Containers release 3.0.16!.

For this release we have updated virtcontainers package which provides important refactoring of the code regarding the proxy and shim interfaces. Our documentation was updated to remove references to Clear Containers proxy service (now each VM has its own proxy).  The collect-data script now collects Kata Containers data. Finally, now the kernel params line options defined in Clear Containers configuration file will take priority over defaults defined by the runtime.

## Changes
- scripts: Ignore qemu startup message
- scripts: Fix collect script bug URL
- cc-env: Remove "CC" from output.
- vendor: Update vendoring
- docs: remove references to Clear Containers proxy service
- cc-check: Document "unrestricted_guest" requirement
- scripts: Update collect script for Kata
- config: Allow user-specified kernel params to take priority
- usage: Show project URL in help output

## Shortlog
0f8b25d scripts: Ignore qemu startup message
ab1a9f1 build: Add bug URL to help output
719f523 scripts: Fix collect script bug URL
1412ff8 cc-env: Remove "CC" from output.
5e7d03c vendor: Update virtcontainers vendoring
f515c21 vendor: Update Gopkg.toml for new prune syntax
ef63d36 vendor: Remove constraints from packages not directly vendored
e65682c docs: remove references to Clear Containers proxy service
93c71c9 cc-check: Document "unrestricted_guest" requirement
7310433 scripts: Update collect script for Kata
feed1be config: Allow user-specified kernel params to take priority
e7de45d usage: Show project URL in help output

## Compatibility with Docker
Clear Containers 3.0.16 is compatible with Docker v17.12-ce
## OCI Runtime Specification
Clear Containers 3.0.16 support the OCI Runtime Specification [v1.0.0-rc5][ocispec]

## Clear Linux Containers image
Clear Containers 3.0.16 requires at least Clear Linux containers image [19350][clearlinuximage]

## Clear Linux Containers Kernel
Clear Containers 3.0.16 requires at least Clear Linux Containers  kernel [v4.9.60-84.container][kernel]

## Installation

- [BC-Linux][bclinux]
- [Centos][centos]
- [Clear Linux][clearlinux]
- [Fedora][fedora]
- [SLES][sles]
- [Ubuntu][ubuntu]

- [Developers][developers]

### Docker swarm support
See issue [\#771](https://github.com/clearcontainers/runtime/issues/771) for more
#### `docker run --cpus=`
See issue [\#341](https://github.com/clearcontainers/runtime/issues/341) for more information.
#### `docker run --kernel-memory=`
See issue [\#388](https://github.com/clearcontainers/runtime/issues/388) for more information.
#### Capabilities
See issue [\#51](https://github.com/clearcontainers/runtime/issues/51) for more information.
#### `docker stats`
See issue [\#200](https://github.com/clearcontainers/runtime/issues/200) for more information.
#### `ps` command
See issue [\#95](https://github.com/clearcontainers/runtime/issues/95) for more information.
#### `events` command
See issue [\#379](https://github.com/clearcontainers/runtime/issues/379) for more information.
#### `update` command
See issue [\#380](https://github.com/clearcontainers/runtime/issues/380) for more information.
### Host `rdmsr` warnings
More information [Limitations][limitations]

[clearlinuximage]: https://download.clearlinux.org/releases/19350/clear/clear-19350-containers.img.xz
[kernel]: https://github.com/clearcontainers/linux/tree/v4.9.60-84.container
[ocispec]: https://github.com/opencontainers/runtime-spec/releases/tag/v1.0.0-rc5
[limitations]: https://github.com/clearcontainers/runtime/blob/082d104e00eac5937c461e502a8fb9984f308ee3/docs/limitations.md
[ubuntu]: https://github.com/clearcontainers/runtime/blob/082d104e00eac5937c461e502a8fb9984f308ee3/docs/ubuntu-installation-guide.md
[fedora]: https://github.com/clearcontainers/runtime/blob/082d104e00eac5937c461e502a8fb9984f308ee3/docs/fedora-installation-guide.md
[centos]: https://github.com/clearcontainers/runtime/blob/082d104e00eac5937c461e502a8fb9984f308ee3/docs/centos-installation-guide.md
[sles]: https://github.com/clearcontainers/runtime/blob/082d104e00eac5937c461e502a8fb9984f308ee3/docs/sles-installation-guide.md
[clearlinux]: https://github.com/clearcontainers/runtime/blob/082d104e00eac5937c461e502a8fb9984f308ee3/docs/clearlinux-installation-guide.md
[bclinux]: https://github.com/clearcontainers/runtime/blob/082d104e00eac5937c461e502a8fb9984f308ee3/docs/bclinux-installation-guide.md
[developers]: https://github.com/clearcontainers/runtime/blob/082d104e00eac5937c461e502a8fb9984f308ee3/docs/developers-clear-containers-install.md

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by jcvenegas** [comment]
docker  pull failed:
```
19:08:21 Running command '/usr/bin/docker [docker pull fedora]'
19:08:24 command failed error 'exit status 1'
19:08:24 [docker pull fedora]
19:08:24 Timeout: 600 seconds
19:08:24 Exit Code: 1
19:08:24 Stdout: Using default tag: latest
19:08:24 latest: Pulling from library/fedora
19:08:24 a8ee583972c2: Pulling fs layer
19:08:24 
19:08:24 Stderr: error pulling image configuration: Get https://registry-1.docker.io/v2/library/fedora/blobs/sha256:422dc563ca3260ad9ef5c47a1c246f5065d7f177ce51f4dd208efd82967ff182: EOF
19:08:24 
19:08:24 --- FAIL: TestIntegration (20.26s)
19:08:24 	main_test.go:55: failed to pull docker image: fedora
19:08:24 FAIL
19:08:24 
```
job restarted

**Comment by grahamwhaley** [comment]
I'll note, it looks like the metrics CI failed in some odd way - I'll go check that out - no doubt spurious and not related to this PR.

**Comment by grahamwhaley** [comment]
Just to update on the metrics CI status - this failed due to timeouts trying to connect to the docker hub.

**Pull request merged**
