### PR TITLE
docs: Reference the code of conduct doc in the contributing doc

### LINKED ISSUE #535: Add link to code of conduct doc in contributing doc
There needs to be a clear link to the projects code of conduct in the contribution document.

### PR DESCRIPTION
**Pull request by jodh-intel**
Potential contributors need to be aware of and agree to the projects
code of conduct before making contributions.

Fixes #535.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
This was mentioned in https://github.com/clearcontainers/runtime/pull/456#issuecomment-328043752, but seems to have slipped through the cracks.

I think it makes more sense to put the link in the contributing doc but we could always add to the README too I guess.

**Comment by jodh-intel** [comment]
@iphutch - please can you review?

**Comment by amshinde** [comment]
lgtm

**Comment by jodh-intel** [comment]
One more ack required.

**Pull request merged**
