### PR TITLE
vendor: Update virtcontainers vendoring

### LINKED ISSUE #900: Vendor virtcontainers and fix the build
Revendor virtcontainers to include most recent patches, particularly Kata agent and shim support.

### PR DESCRIPTION
**Pull request by sboeuf**
vendor: Update virtcontainers vendoring
    
This commit update virtcontainers vendoring by mainly adding support
for kata agent and kata shim.
    
Shortlog:
    
    3e86f7b vendor: Force kata containers agent vendoring
    34952bb shim: Factorize the shim config structure between kata and CC
    a7e244a shim: Factorize shim execution code
    eb8befb shim: Add a Kata shim mock implementation
    6da9685 shim: Add a Kata Containers shim type
    18f46de kata_shim: Initial implementation
    60a446a container: Generate process token when not set
    4c2c9a4 mounts: Fix bug while checking if /dev was bind-mounted
    67fcb6d pkg/oci: honour CPU period and quota
    1a3de59 agent: Add kata exec, stopContainer and killContainer
    4f92997 annotations: Update tests to use package prefix
    b3da3de mount: Fix tests for bindMountContainerRootfs function
    aa75a0e kata_agent: Implement vmURL and setProxyURL
    53f093d kata_agent: Initial VSOCK support
    bc302d2 kata_agent: Implement the validate function
    cb7fac2 kata_agent: Rename shared dir paths
    0b95eda kata_agent: Create and start container implementations
    c4a4be4 mount: Gather the entire bind mount API
    be96f34 vendor: Update for Kata Containers
    c0692ca annotations: Move OCI annotations to the annotation package
    1a638c0 ci: Handle complex revendoring cases
    fe726af kata_agent: Implement pod start and stop ops
    3d1afe4 kata_agent: Initialize gRPC client
    f6948d8 agent: Add new agent type for Kata Containers
    7d35db6 kata_agent: Add Kata agent configuration
    b2fe3df hyperstart: Rename to hyperstart_agent
    f86cd11 kata_agent: Initial implementation
    414e156 qemu: improve kernel boot time
    bdde7bb pod: Add important comment for Cmd type
    a217958 oci: Pass the NoNewPrivileges flag to the agent.
    f683602 oci: Add support for NoNewPrivileges in oci spec
    ddd89b7 cheanup: Remove vendored "golang.org/x/crypto" package.
    fd6e357 cleanup: Remove sshd agent
    b7c19b8 cni: update function names for consistency
    847eaaa network: scan network one less time
    dc4836a network: unique ID is not unique
    8449f56 network: refactoring and cleanup of CNI path
    d6f9690 vendor: Revendor govmm for VSOCK support
    
Fixes #900
   
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by jodh-intel** [comment]
lgtm

(fyi, if you indent the commit range with a few spaces, it gets rendered in a fixed font on github which looks better as all the commits line up nicely :)

**Comment by sameo** [comment]
Fedora's CI fails on Openshift. I think we can merge that one.

**Comment by jodh-intel** [comment]
Agreed - the F26 failure seems to be https://github.com/clearcontainers/jenkins/issues/32 again.

**Pull request merged**
